--- Module heroku is a set of wrappers around the Go heroku client.
-- @module heroku

local heroku = {}

--- Authentication functions.
-- @section auth

--- create_token creates a new API token for the current user using the global credentials.
-- Tokens generated by this function are valid for 30 days.
-- @usage local tok = heroku.create_token()

--- get_userpass returns the current global username and password/api token.
-- By default this data is sourced from the user's netrc.
-- @return string heroku account email address
-- @return string heroku token
function heroku.get_userpass()
  return "", ""
end

--- set_userpass sets the global username and password with given values.
-- @param username the heroku account email address
-- @param token the heroku token
function heroku.set_userpass(username, token)
end

--- Apps.
-- @section apps

--- app_create creates a new heroku application with an optional name.
-- By default all apps are created on cedar in the US.
-- @param name an optional name for the app.
-- @return @{App}
function heroku.app_create(name)
end

--- app_info fetches application info from the heroku API.
-- @param name the heroku application name
-- @return @{App}
function heroku.app_info(name)
end

--- app_destroy destroys a heroku application and any of the addons it owns.
-- There is no going back if you do this carelessly. Be warned.
-- @param name the heroku application name
-- @return @{App}
function heroku.app_destroy(name)
end



--- Types
-- @section types

--- App is a single heroku application.
-- It is based on the App type in the heroku Go client: https://godoc.org/github.com/cyberdelia/heroku-go/v3#App
-- @type App
local App = {}

--- acm is set if the app uses automatic certificate management (let's encrypt).
App.acm = false

--- git_url is the url that the app can be git pulled from or pushed to.
App.git_url = ""

--- owner is the owner of the app.
-- This is a small table with two fields: email (of the user), and id (of the user).
App.owner = {}

--- region is the geographic region this app is being run in.
-- This is a small table with two fields: name (of the region), and id (of the region).
App.region = {}

--- repo_size is the size in bytes of the git repository for this app.
App.repo_size = 0

--- slug_size is the size of the latest slug generated in the build process in bytes.
App.slug_size = 0

--- stack is the heroku application stack the app is built on top of.
-- This is a small table with two fields: name (of the stack), and id (of the stack).
App.stack = {}

--- web_url is the HTTP URL for this app.
App.web_url = ""

return heroku
